### ISSUE TITLE
Defensiveness

### ISSUE THREAD

**Issue by kepop1** [ivnkris/code-quiz#1]
https://github.com/ivnkris/code-quiz/blob/0101bf9bdc42b51fdd45dc88ee8b092c7c6f9a8c/assets/js/highscore-script.js#L23

So of there are no highscores present, this will try and remove a DOM element that isn't there. We could probably use some kind of if condition to check the DOM node exists.

**Comment by ivnkris** [comment]
added if condition to check if DOM element exists
